"""Auditable command catalog for both CC2 camera updater stages.

This module is the public, side-effect-free command layer.  It deliberately
contains no HID device discovery and performs no USB I/O.  A caller can inspect
the catalogs or build exact wire reports without connecting a camera; sending a
report is an explicit operation in :mod:`cc2camera.hid_transport`.

The names and values below mirror ``PROTOCOL.md`` and the annotated source in
``source-reconstruction/``.  They are firmware-specific to the analyzed
``/bin/hid_update`` and U-Boot binaries, not a promise about other CC2 firmware.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum, IntEnum
from types import MappingProxyType
import re
import struct
from typing import Mapping

from .protocol import (
    BOOT_DATA_SIZE,
    BootFrame,
    ProtocolError,
    UPGRADE_MODE_CDC,
    UPGRADE_MODE_HID,
    UpdatePlan,
    build_boot_frame,
    build_metadata_frame,
    build_normal_report,
    from_boot_hid_report,
    parse_boot_frame,
    upgrade_flag_payload,
)


__all__ = [
    "ADB_UPLOAD_COMMAND_TARGET",
    "BOOT_FRAME_TYPES",
    "CONFIGURATION_BY_KEY",
    "CONFIGURATION_COMMANDS",
    "DERIVED_UPLOAD_TARGET_COMMANDS",
    "LITERAL_UPLOAD_TARGET_COMMANDS",
    "NORMAL_COMMAND_BY_VALUE",
    "NORMAL_COMMAND_CATALOG",
    "NORMAL_DISPATCH_MAP",
    "UPLOAD_COMMANDS",
    "BootFrameType",
    "BootFrameTypeDescriptor",
    "ConfigCommandPair",
    "ConfigurationKey",
    "NormalCommand",
    "NormalCommandDescriptor",
    "NormalCommandFamily",
    "NormalDispatchBehavior",
    "NormalFrameType",
    "NormalStatus",
    "UploadCommandDescriptor",
    "UploadState",
    "build_boot_data_request",
    "build_boot_metadata_request",
    "build_adb_upload_command_target_request",
    "build_config_get_request",
    "build_config_set_request",
    "build_upgrade_request",
    "build_upload_commit_request",
    "build_upload_data_request",
    "build_upload_initialize_request",
    "build_upload_target_request",
    "build_version_request",
    "decode_boot_ack",
    "decode_boot_terminal_status",
    "describe_normal_command",
    "is_upgrade_trigger_command",
]


# ---------------------------------------------------------------------------
# Normal Linux HID: framing vocabulary and dispatcher behavior
# ---------------------------------------------------------------------------
#
# Binary anchor: hid_update dispatch_normal_report() at 0x0040123c.
#
# Requests and responses are 1,024 bytes.  The request field at offset 8 is an
# auxiliary value (used as the absolute upload-packet number by 0x3200); the
# same four bytes are a status code in replies.  Frame type 1 means a normal or
# continuing payload and type 2 marks the final upload packet.  Although the
# target parser fails to reject other type values, those values remove payload
# bytes from CRC coverage and must never be emitted by this library.


class NormalFrameType(IntEnum):
    """Only the two request frame types safe for a producer to emit."""

    PAYLOAD_OR_CONTINUATION = 1
    FINAL_PAYLOAD = 2


class NormalStatus(IntEnum):
    """Status values generated by the Linux daemon's response constructor."""

    SUCCESS = 0
    HANDLER_FAILURE = 1
    BAD_REPORT_ID = 2
    BAD_MAGIC = 3
    BAD_CRC = 4
    UNKNOWN_COMMAND_GROUP = 5


class NormalCommandFamily(str, Enum):
    VERSION = "version"
    CONFIGURATION = "configuration"
    FILE_UPLOAD = "file-upload"
    UPGRADE_TRIGGER = "upgrade-trigger"


@dataclass(frozen=True)
class NormalDispatchBehavior:
    """One high-level branch of the normal-mode command dispatcher."""

    first: int
    last: int
    behavior: str
    response_behavior: str


# This range table is intentionally explicit.  It records negative behavior as
# well as useful commands: 0x1xxx is a silent no-op, unknown values inside the
# 0x2xxx/0x3xxx groups are silent, every 0x4xxx value is destructive, and higher
# groups return status 5.  A host must therefore use timeouts for silent paths.
NORMAL_DISPATCH_MAP = (
    NormalDispatchBehavior(0x0000, 0x0FFF, "only exact 0x0001 is implemented", "other values: no response"),
    NormalDispatchBehavior(0x1000, 0x1FFF, "recognized no-op group", "no response"),
    NormalDispatchBehavior(0x2000, 0x2FFF, "listed configuration commands only", "unknown values: no response"),
    NormalDispatchBehavior(0x3000, 0x3FFF, "listed upload commands only", "unknown values: no response"),
    NormalDispatchBehavior(0x4000, 0x4FFF, "write upgrade words and reboot", "status 0/1, then reboot"),
    NormalDispatchBehavior(0x5000, 0xFFFF, "unknown command group", "status 5"),
)


# ---------------------------------------------------------------------------
# Exact normal-mode command numbers
# ---------------------------------------------------------------------------
#
# Proof-reading note: every exact command accepted by the analyzed binary is
# declared once in this enum.  Configuration pairs are repeated in the compact
# CONFIGURATION_COMMANDS table below so a reviewer can verify key-to-wire-value
# mappings without following code.  Tests assert uniqueness and completeness.


class NormalCommand(IntEnum):
    VERSION_QUERY = 0x0001

    CONFIG_GET_MANUFACTURER_LABEL = 0x2000
    CONFIG_SET_MANUFACTURER_LABEL = 0x2001
    CONFIG_GET_SERIAL_LABEL = 0x2010
    CONFIG_SET_SERIAL_LABEL = 0x2011
    CONFIG_GET_PRODUCT_NUMBER = 0x2020
    CONFIG_SET_PRODUCT_NUMBER = 0x2021
    CONFIG_GET_VENDOR_ID = 0x2030
    CONFIG_SET_VENDOR_ID = 0x2031
    CONFIG_GET_PRODUCT_ID = 0x2040
    CONFIG_SET_PRODUCT_ID = 0x2041
    CONFIG_GET_DEVICE_BCD = 0x2050
    CONFIG_SET_DEVICE_BCD = 0x2051

    CONFIG_GET_MODEL_LABEL = 0x2F00
    CONFIG_SET_MODEL_LABEL = 0x2F01
    CONFIG_GET_CMEI_LABEL = 0x2F10
    CONFIG_SET_CMEI_LABEL = 0x2F11
    CONFIG_GET_APP_KEY = 0x2F20
    CONFIG_SET_APP_KEY = 0x2F21
    CONFIG_GET_PRODUCT_LABEL = 0x2F30
    CONFIG_SET_PRODUCT_LABEL = 0x2F31
    CONFIG_GET_ADB_ENABLED = 0x2F40
    CONFIG_SET_ADB_ENABLED = 0x2F41
    CONFIG_GET_SENSOR_NAME = 0x2F50
    CONFIG_SET_SENSOR_NAME = 0x2F51
    CONFIG_GET_I2C_ADDRESS = 0x2F60
    CONFIG_SET_I2C_ADDRESS = 0x2F61
    CONFIG_GET_DEFAULT_BOOT = 0x2F70
    CONFIG_SET_DEFAULT_BOOT = 0x2F71
    CONFIG_GET_SENSOR_FPS = 0x2F80
    CONFIG_SET_SENSOR_FPS = 0x2F81
    CONFIG_GET_SENSOR_WIDTH = 0x2F90
    CONFIG_SET_SENSOR_WIDTH = 0x2F91
    CONFIG_GET_SENSOR_HEIGHT = 0x2FA0
    CONFIG_SET_SENSOR_HEIGHT = 0x2FA1
    CONFIG_GET_HV_FLIP = 0x2FB0
    CONFIG_SET_HV_FLIP = 0x2FB1
    CONFIG_GET_RATE_CONTROL_MODE = 0x2FC0
    CONFIG_SET_RATE_CONTROL_MODE = 0x2FC1
    CONFIG_GET_BITRATE = 0x2FD0
    CONFIG_SET_BITRATE = 0x2FD1
    CONFIG_GET_QP_VALUE = 0x2FE0
    CONFIG_SET_QP_VALUE = 0x2FE1

    UPLOAD_INITIALIZE = 0x3000
    UPLOAD_TARGET_3110 = 0x3110
    UPLOAD_TARGET_3111 = 0x3111
    UPLOAD_TARGET_3112 = 0x3112
    UPLOAD_TARGET_3113 = 0x3113
    UPLOAD_TARGET_SENSOR_MODULE = 0x3114
    UPLOAD_TARGET_SENSOR_CONFIGURATION = 0x3115
    UPLOAD_TARGET_3116 = 0x3116
    UPLOAD_TARGET_3120 = 0x3120
    UPLOAD_TARGET_3150 = 0x3150
    UPLOAD_TARGET_31F0 = 0x31F0
    UPLOAD_APPEND_DATA = 0x3200
    UPLOAD_COMMIT = 0x3300

    # 0x4000 is merely the conventional value.  The binary masks only the high
    # nibble, so build_upgrade_request() deliberately accepts all 0x4xxx values.
    UPGRADE_AND_REBOOT = 0x4000


# ---------------------------------------------------------------------------
# Complete configuration GET/SET table
# ---------------------------------------------------------------------------
#
# Binary anchors: dispatch table at 0x004024c0, GET at 0x00401cd0, and SET at
# 0x00402038.  Every even command reads one literal key from
# /etc/conf.d/uvc.config; the following odd command rewrites that key.
#
# The target performs no type, range, or encoding validation.  Its SET routine
# uses undersized fixed buffers and zero-pads instead of truncating when a new
# value is shorter.  The builders preserve the raw protocol but callers should
# send short textual values only.  A builder succeeding says nothing about the
# semantic safety of the value or whether the key exists on a particular unit.


class ConfigurationKey(str, Enum):
    MANUFACTURER_LABEL = "manufact_lab"
    SERIAL_LABEL = "serial_lab"
    PRODUCT_NUMBER = "productnumber"
    VENDOR_ID = "vendor_id"
    PRODUCT_ID = "product_id"
    DEVICE_BCD = "device_bcd"
    MODEL_LABEL = "model_lab"
    CMEI_LABEL = "cmei_lab"
    APP_KEY = "appkey"
    PRODUCT_LABEL = "product_lab"
    ADB_ENABLED = "adb_en"
    SENSOR_NAME = "sensor_name"
    I2C_ADDRESS = "i2c_addr"
    DEFAULT_BOOT = "default_boot"
    SENSOR_FPS = "sensor_fps"
    SENSOR_WIDTH = "sensor_width"
    SENSOR_HEIGHT = "sensor_height"
    HV_FLIP = "hvflip"
    RATE_CONTROL_MODE = "rcmode"
    BITRATE = "bitrate"
    QP_VALUE = "qp_value"


@dataclass(frozen=True)
class ConfigCommandPair:
    key: ConfigurationKey
    get: NormalCommand
    set: NormalCommand
    present_in_supplied_active_config: bool


CONFIGURATION_COMMANDS = (
    ConfigCommandPair(
        ConfigurationKey.MANUFACTURER_LABEL,
        NormalCommand.CONFIG_GET_MANUFACTURER_LABEL,
        NormalCommand.CONFIG_SET_MANUFACTURER_LABEL,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.SERIAL_LABEL,
        NormalCommand.CONFIG_GET_SERIAL_LABEL,
        NormalCommand.CONFIG_SET_SERIAL_LABEL,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.PRODUCT_NUMBER,
        NormalCommand.CONFIG_GET_PRODUCT_NUMBER,
        NormalCommand.CONFIG_SET_PRODUCT_NUMBER,
        False,
    ),
    ConfigCommandPair(
        ConfigurationKey.VENDOR_ID,
        NormalCommand.CONFIG_GET_VENDOR_ID,
        NormalCommand.CONFIG_SET_VENDOR_ID,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.PRODUCT_ID,
        NormalCommand.CONFIG_GET_PRODUCT_ID,
        NormalCommand.CONFIG_SET_PRODUCT_ID,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.DEVICE_BCD,
        NormalCommand.CONFIG_GET_DEVICE_BCD,
        NormalCommand.CONFIG_SET_DEVICE_BCD,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.MODEL_LABEL,
        NormalCommand.CONFIG_GET_MODEL_LABEL,
        NormalCommand.CONFIG_SET_MODEL_LABEL,
        False,
    ),
    ConfigCommandPair(
        ConfigurationKey.CMEI_LABEL,
        NormalCommand.CONFIG_GET_CMEI_LABEL,
        NormalCommand.CONFIG_SET_CMEI_LABEL,
        False,
    ),
    ConfigCommandPair(
        ConfigurationKey.APP_KEY,
        NormalCommand.CONFIG_GET_APP_KEY,
        NormalCommand.CONFIG_SET_APP_KEY,
        False,
    ),
    ConfigCommandPair(
        ConfigurationKey.PRODUCT_LABEL,
        NormalCommand.CONFIG_GET_PRODUCT_LABEL,
        NormalCommand.CONFIG_SET_PRODUCT_LABEL,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.ADB_ENABLED,
        NormalCommand.CONFIG_GET_ADB_ENABLED,
        NormalCommand.CONFIG_SET_ADB_ENABLED,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.SENSOR_NAME,
        NormalCommand.CONFIG_GET_SENSOR_NAME,
        NormalCommand.CONFIG_SET_SENSOR_NAME,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.I2C_ADDRESS,
        NormalCommand.CONFIG_GET_I2C_ADDRESS,
        NormalCommand.CONFIG_SET_I2C_ADDRESS,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.DEFAULT_BOOT,
        NormalCommand.CONFIG_GET_DEFAULT_BOOT,
        NormalCommand.CONFIG_SET_DEFAULT_BOOT,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.SENSOR_FPS,
        NormalCommand.CONFIG_GET_SENSOR_FPS,
        NormalCommand.CONFIG_SET_SENSOR_FPS,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.SENSOR_WIDTH,
        NormalCommand.CONFIG_GET_SENSOR_WIDTH,
        NormalCommand.CONFIG_SET_SENSOR_WIDTH,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.SENSOR_HEIGHT,
        NormalCommand.CONFIG_GET_SENSOR_HEIGHT,
        NormalCommand.CONFIG_SET_SENSOR_HEIGHT,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.HV_FLIP,
        NormalCommand.CONFIG_GET_HV_FLIP,
        NormalCommand.CONFIG_SET_HV_FLIP,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.RATE_CONTROL_MODE,
        NormalCommand.CONFIG_GET_RATE_CONTROL_MODE,
        NormalCommand.CONFIG_SET_RATE_CONTROL_MODE,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.BITRATE,
        NormalCommand.CONFIG_GET_BITRATE,
        NormalCommand.CONFIG_SET_BITRATE,
        True,
    ),
    ConfigCommandPair(
        ConfigurationKey.QP_VALUE,
        NormalCommand.CONFIG_GET_QP_VALUE,
        NormalCommand.CONFIG_SET_QP_VALUE,
        True,
    ),
)

CONFIGURATION_BY_KEY: Mapping[ConfigurationKey, ConfigCommandPair] = MappingProxyType(
    {entry.key: entry for entry in CONFIGURATION_COMMANDS}
)


# ---------------------------------------------------------------------------
# Complete arbitrary-file upload state machine
# ---------------------------------------------------------------------------
#
# Binary anchors: initialize 0x00402830, append 0x004028dc, commit 0x004029f0,
# derived sensor paths 0x00402ba8, and dispatcher 0x00402e3c.
#
# There are exactly thirteen accepted command values.  Eight target commands
# consume a literal path, two derive a path from sensor_name, and the remaining
# three initialize, append, and commit.  Numeric distinctions among the eight
# literal-path selectors have no observable effect in this firmware build.
#
# Commit is highly privileged: it interpolates the path into unquoted shell
# commands, removes the existing target, writes a new file, and chmods it 0777.
# These builders only serialize frames.  They do not make that operation safe,
# authenticated, atomic, or reversible, and this protocol has no file-read API.


class UploadState(IntEnum):
    IDLE = 1
    NEED_TARGET = 2
    RECEIVING = 3
    READY_TO_COMMIT = 4
    ERROR = 5


@dataclass(frozen=True)
class UploadCommandDescriptor:
    command: NormalCommand
    required_state: UploadState
    operation: str
    normal_next_state: UploadState
    accepts_payload: bool
    destructive: bool = False


UPLOAD_COMMANDS = (
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_INITIALIZE,
        UploadState.IDLE,
        "allocate 0x01000200-byte buffer and reset counters",
        UploadState.NEED_TARGET,
        False,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3110,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3111,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3112,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3113,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_SENSOR_MODULE,
        UploadState.NEED_TARGET,
        "derive /system/lib/modules/sensor_%s_t31.ko",
        UploadState.RECEIVING,
        False,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_SENSOR_CONFIGURATION,
        UploadState.NEED_TARGET,
        "derive /system/etc/sensor/%s-t31.bin",
        UploadState.RECEIVING,
        False,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3116,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3120,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_3150,
        UploadState.NEED_TARGET,
        "select literal destination path through equivalent handler",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_TARGET_31F0,
        UploadState.NEED_TARGET,
        "select literal destination path",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_APPEND_DATA,
        UploadState.RECEIVING,
        "append absolute-sequence-numbered data; type 2 marks final",
        UploadState.RECEIVING,
        True,
    ),
    UploadCommandDescriptor(
        NormalCommand.UPLOAD_COMMIT,
        UploadState.READY_TO_COMMIT,
        "remove target, write bytes, and chmod 0777",
        UploadState.IDLE,
        False,
        True,
    ),
)

LITERAL_UPLOAD_TARGET_COMMANDS = frozenset(
    {
        NormalCommand.UPLOAD_TARGET_3110,
        NormalCommand.UPLOAD_TARGET_3111,
        NormalCommand.UPLOAD_TARGET_3112,
        NormalCommand.UPLOAD_TARGET_3113,
        NormalCommand.UPLOAD_TARGET_3116,
        NormalCommand.UPLOAD_TARGET_3120,
        NormalCommand.UPLOAD_TARGET_3150,
        NormalCommand.UPLOAD_TARGET_31F0,
    }
)
DERIVED_UPLOAD_TARGET_COMMANDS = frozenset(
    {
        NormalCommand.UPLOAD_TARGET_SENSOR_MODULE,
        NormalCommand.UPLOAD_TARGET_SENSOR_CONFIGURATION,
    }
)


# ---------------------------------------------------------------------------
# Unified normal-command catalog
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class NormalCommandDescriptor:
    command: int
    name: str
    family: NormalCommandFamily
    request: str
    success_response: str
    side_effect: str
    source_anchor: str


def _build_normal_catalog() -> tuple[NormalCommandDescriptor, ...]:
    entries = [
        NormalCommandDescriptor(
            NormalCommand.VERSION_QUERY,
            "version_query",
            NormalCommandFamily.VERSION,
            "empty payload (extra bytes are ignored by firmware)",
            "type 1, status 0, first line of /tmp/version.txt",
            "none",
            "hid_update 0x004015e4",
        )
    ]
    for pair in CONFIGURATION_COMMANDS:
        entries.extend(
            (
                NormalCommandDescriptor(
                    pair.get,
                    f"config_get_{pair.key.value}",
                    NormalCommandFamily.CONFIGURATION,
                    "empty payload (payload is ignored)",
                    "type 1, status 0, raw value bytes",
                    "none",
                    "hid_update GET 0x00401cd0 / dispatcher 0x004024c0",
                ),
                NormalCommandDescriptor(
                    pair.set,
                    f"config_set_{pair.key.value}",
                    NormalCommandFamily.CONFIGURATION,
                    "replacement value bytes; frame type 1 or 2",
                    "type 0, status 0",
                    f"rewrites {pair.key.value} in persistent uvc.config",
                    "hid_update SET 0x00402038 / dispatcher 0x004024c0",
                ),
            )
        )
    for upload in UPLOAD_COMMANDS:
        entries.append(
            NormalCommandDescriptor(
                upload.command,
                upload.command.name.lower(),
                NormalCommandFamily.FILE_UPLOAD,
                upload.operation,
                "type 0, status 0 (wrong-state calls can falsely succeed)",
                "destructive file replacement" if upload.destructive else "changes uploader state or buffers data",
                "hid_update dispatcher 0x00402e3c",
            )
        )
    entries.append(
        NormalCommandDescriptor(
            NormalCommand.UPGRADE_AND_REBOOT,
            "upgrade_and_reboot",
            NormalCommandFamily.UPGRADE_TRIGGER,
            "exactly 8 upgrade-word bytes; canonical command 0x4000",
            "type 0, status 0 on write success; reboot follows even on failure",
            "writes flash 0x7f8000 and reboots into U-Boot updater",
            "hid_update 0x00401364; group branch 0x0040123c",
        )
    )
    return tuple(entries)


NORMAL_COMMAND_CATALOG = _build_normal_catalog()
NORMAL_COMMAND_BY_VALUE: Mapping[int, NormalCommandDescriptor] = MappingProxyType(
    {int(entry.command): entry for entry in NORMAL_COMMAND_CATALOG}
)


def is_upgrade_trigger_command(command: int) -> bool:
    """Return true for every value routed to the destructive 0x4xxx branch."""

    return isinstance(command, int) and 0 <= command <= 0xFFFF and command & 0xF000 == 0x4000


def describe_normal_command(command: int) -> NormalCommandDescriptor | None:
    """Describe an exact recovered command, including noncanonical 0x4xxx.

    ``None`` means the value has no implemented command handler.  Consult
    ``NORMAL_DISPATCH_MAP`` to distinguish silent no-op/no-response values from
    values that elicit status 5.
    """

    exact = NORMAL_COMMAND_BY_VALUE.get(command)
    if exact is not None:
        return exact
    if is_upgrade_trigger_command(command):
        canonical = NORMAL_COMMAND_BY_VALUE[int(NormalCommand.UPGRADE_AND_REBOOT)]
        return NormalCommandDescriptor(
            command,
            f"upgrade_and_reboot_0x{command:04x}",
            canonical.family,
            canonical.request,
            canonical.success_response,
            canonical.side_effect,
            canonical.source_anchor,
        )
    return None


# ---------------------------------------------------------------------------
# Side-effect-free normal-report builders
# ---------------------------------------------------------------------------


def _raw_payload(value: str | bytes | bytearray | memoryview, *, field: str) -> bytes:
    if isinstance(value, str):
        return value.encode("utf-8")
    if isinstance(value, (bytes, bytearray, memoryview)):
        return bytes(value)
    raise ProtocolError(f"{field} must be str or bytes-like")


def _configuration_pair(key: ConfigurationKey | str) -> ConfigCommandPair:
    try:
        normalized = key if isinstance(key, ConfigurationKey) else ConfigurationKey(key)
    except (TypeError, ValueError) as exc:
        raise ProtocolError(f"unknown configuration key: {key!r}") from exc
    return CONFIGURATION_BY_KEY[normalized]


def build_version_request() -> bytes:
    """Build exact command 0x0001; the request needs no payload."""

    return build_normal_report(NormalCommand.VERSION_QUERY)


def build_config_get_request(key: ConfigurationKey | str) -> bytes:
    """Build the even GET command for one recovered configuration key."""

    return build_normal_report(_configuration_pair(key).get)


def build_config_set_request(
    key: ConfigurationKey | str,
    value: str | bytes | bytearray | memoryview,
    *,
    frame_type: NormalFrameType = NormalFrameType.PAYLOAD_OR_CONTINUATION,
) -> bytes:
    """Build the odd SET command without guessing the value's semantics.

    UTF-8 is used when ``value`` is a string.  Bytes-like input is preserved
    exactly.  The target does no validation and has unsafe fixed buffers, so the
    caller remains responsible for choosing a short, appropriate textual value.
    """

    return build_normal_report(
        _configuration_pair(key).set,
        _raw_payload(value, field="configuration value"),
        frame_type=int(frame_type),
    )


_SAFE_UPLOAD_PATH = re.compile(rb"\A[A-Za-z0-9_./-]+\Z")


# ---------------------------------------------------------------------------
# Deliberately narrow recovery use of the vendor's shell-injection bug
# ---------------------------------------------------------------------------
#
# Binary anchors:
#   target parsing  0x00402e3c
#   upload commit   0x004029f0
#
# The generic build_upload_target_request() below intentionally rejects shell
# metacharacters.  Weakening that validation would turn every caller into a
# potential command-injection producer.  This one immutable target is exposed
# separately because it is useful for a specific, audited recovery operation:
# start the stock /bin/adbd once without creating a persistent startup file.
#
# The target contains no literal spaces because hid_update truncates the target
# at the first ASCII space.  On 0x3300, its unquoted `system("rm %s")` becomes:
#
#   rm /tmp/.cc2flash-adbd-bootstrap;/bin/adbd&
#
# The following fopen() receives the *literal* full target.  Its embedded
# `/bin/...` makes `/tmp/.cc2flash-adbd-bootstrap;` an intermediate directory;
# that directory does not exist on the stock tmpfs, so fopen fails after adbd
# has already been launched.  This expected commit failure also prevents the
# later unquoted chmod command from launching adbd a second time.
#
# This is firmware-specific behavior, not a general shell-command API.  Keep
# the value constant, below the daemon's 128-byte target buffer, and free of
# literal whitespace.
# Keep the hardware-validated wire payload independent of the CLI name.
ADB_UPLOAD_COMMAND_TARGET = b"/tmp/.cc2flash-adbd-bootstrap;/bin/adbd&"


def build_adb_upload_command_target_request() -> bytes:
    """Build the one audited 0x3110 target that starts stock ``/bin/adbd``.

    Building the report performs no I/O.  Sending it as part of an upload
    transaction deliberately relies on the analyzed daemon's unquoted shell
    command.  Callers must expect the later 0x3300 commit to fail or disconnect
    after the process has been started.
    """

    assert b" " not in ADB_UPLOAD_COMMAND_TARGET
    assert 0 < len(ADB_UPLOAD_COMMAND_TARGET) <= 127
    return build_normal_report(
        NormalCommand.UPLOAD_TARGET_3110,
        ADB_UPLOAD_COMMAND_TARGET,
    )


def build_upload_initialize_request() -> bytes:
    """Build 0x3000, valid only while the device uploader is idle."""

    return build_normal_report(NormalCommand.UPLOAD_INITIALIZE)


def build_upload_target_request(
    command: NormalCommand | int,
    path: str | bytes | bytearray | memoryview | None = None,
) -> bytes:
    """Build any of the ten recovered destination-selection commands.

    The eight literal-path commands require a 1..127 byte safe ASCII path.  The
    two sensor-derived commands (0x3114/0x3115) require ``path=None`` because the
    camera constructs their paths from ``sensor_name``.  This intentionally
    excludes spaces and shell metacharacters that the vulnerable target would
    otherwise interpolate into unquoted ``rm`` and ``chmod`` commands.
    """

    try:
        selected = NormalCommand(command)
    except (TypeError, ValueError) as exc:
        raise ProtocolError(f"unknown upload target command: {command!r}") from exc

    if selected in DERIVED_UPLOAD_TARGET_COMMANDS:
        if path is not None:
            raise ProtocolError("sensor-derived upload target must not include a path")
        return build_normal_report(selected)
    if selected not in LITERAL_UPLOAD_TARGET_COMMANDS:
        raise ProtocolError(f"0x{int(selected):04x} is not an upload target command")
    if path is None:
        raise ProtocolError("literal upload target requires a path")

    try:
        encoded = path.encode("ascii") if isinstance(path, str) else bytes(path)
    except (UnicodeEncodeError, TypeError) as exc:
        raise ProtocolError("upload path must be ASCII or bytes-like") from exc
    if not encoded or len(encoded) > 127 or _SAFE_UPLOAD_PATH.fullmatch(encoded) is None:
        raise ProtocolError("upload path must be 1-127 safe ASCII path bytes")
    return build_normal_report(selected, encoded)


def build_upload_data_request(
    sequence: int,
    data: bytes | bytearray | memoryview,
    *,
    final: bool,
) -> bytes:
    """Build 0x3200 with its absolute sequence in the auxiliary field.

    Sequence values are absolute and zero-based.  A nonfinal frame is type 1;
    a final frame is type 2 and moves the target to ready-to-commit.  Zero-byte
    data is representable by the firmware and therefore remains representable
    here, although the high-level ``upload_normal_file`` helper rejects empty
    complete files as a separate policy decision.
    """

    if not isinstance(sequence, int) or not 0 <= sequence <= 0xFFFFFFFF:
        raise ProtocolError("upload sequence must fit in an unsigned 32-bit integer")
    try:
        payload = bytes(data)
    except TypeError as exc:
        raise ProtocolError("upload data must be bytes-like") from exc
    return build_normal_report(
        NormalCommand.UPLOAD_APPEND_DATA,
        payload,
        frame_type=int(
            NormalFrameType.FINAL_PAYLOAD if final else NormalFrameType.PAYLOAD_OR_CONTINUATION
        ),
        status=sequence,
    )


def build_upload_commit_request() -> bytes:
    """Build destructive 0x3300; valid only after a final data packet."""

    return build_normal_report(NormalCommand.UPLOAD_COMMIT)


def build_upgrade_request(
    *,
    mode: int = UPGRADE_MODE_HID,
    command: int = NormalCommand.UPGRADE_AND_REBOOT,
) -> bytes:
    """Build the exact eight-byte persistent upgrade-word write and reboot.

    The conventional command is 0x4000, but static analysis proves that every
    0x4xxx value reaches the same branch and echoes the actual value in its
    response.  ``mode`` may select the U-Boot HID or CDC transport.  Building
    this report is harmless; sending it writes flash offset 0x7f8000 and reboots.
    """

    if not is_upgrade_trigger_command(command):
        raise ProtocolError("upgrade trigger command must be in the 0x4xxx group")
    return build_normal_report(command, upgrade_flag_payload(mode))


# ---------------------------------------------------------------------------
# U-Boot updater frame types and typed helpers
# ---------------------------------------------------------------------------
#
# Binary anchor: common updater state machine at U-Boot 0x80117d1c.
#
# U-Boot has no general command word.  The byte at common-frame offset 3 is the
# entire operation namespace.  Only host types 1 and 3 are accepted.  Types 2
# and 5 are device replies.  There is no read, query, cancel, erase-only, reboot,
# partition-selection, signature, or post-write-verification frame type.


class BootFrameType(IntEnum):
    HOST_TRANSFER_METADATA = 1
    DEVICE_NEXT_PACKET_ACK = 2
    HOST_TRANSFER_DATA = 3
    DEVICE_TERMINAL_STATUS = 5


@dataclass(frozen=True)
class BootFrameTypeDescriptor:
    frame_type: BootFrameType
    direction: str
    payload: str
    meaning: str
    source_anchor: str


BOOT_FRAME_TYPES = (
    BootFrameTypeDescriptor(
        BootFrameType.HOST_TRANSFER_METADATA,
        "host -> device",
        "exactly 10 bytes",
        "initialize firmware transfer",
        "U-Boot type-1 branch 0x80117d1c",
    ),
    BootFrameTypeDescriptor(
        BootFrameType.DEVICE_NEXT_PACKET_ACK,
        "device -> host",
        "u32le(next expected absolute packet)",
        "acknowledge or request retransmission",
        "U-Boot send_ack path",
    ),
    BootFrameTypeDescriptor(
        BootFrameType.HOST_TRANSFER_DATA,
        "host -> device",
        "u32le(sequence) plus data",
        "append numbered transfer data",
        "U-Boot type-3 branch 0x80118094",
    ),
    BootFrameTypeDescriptor(
        BootFrameType.DEVICE_TERMINAL_STATUS,
        "device -> host",
        "one byte: 01 success, 00 failure",
        "RAM-image MD5 result, sent before flash erase/write",
        "U-Boot finalization 0x801183b0",
    ),
)


def build_boot_metadata_request(plan: UpdatePlan, *, firmware_version: int = 0) -> bytes:
    """Build the canonical 17-byte host type-1 metadata frame.

    U-Boot itself fails to reject zero divisors or oversized unauthenticated
    allocations.  The public producer closes those holes before serializing a
    frame and also checks that the redundant packet count in ``UpdatePlan`` is
    internally consistent.
    """

    if not 1 <= plan.packet_payload_size <= BOOT_DATA_SIZE:
        raise ProtocolError(
            f"metadata packet payload must be 1..{BOOT_DATA_SIZE} bytes for HID"
        )
    if not 1 <= plan.transfer_size <= 0xFFFFFFFF:
        raise ProtocolError("metadata transfer size must fit in a nonzero u32")
    if not 1 <= plan.packets_per_ack <= 0xFFFF:
        raise ProtocolError("metadata packets-per-ACK must fit in a nonzero u16")
    if not 0 <= firmware_version <= 0xFFFF:
        raise ProtocolError("metadata firmware version must fit in a u16")
    expected_packets = (
        plan.transfer_size + plan.packet_payload_size - 1
    ) // plan.packet_payload_size
    if plan.packet_count != expected_packets:
        raise ProtocolError(
            f"metadata packet count {plan.packet_count} does not match {expected_packets}"
        )

    return build_metadata_frame(plan, firmware_version=firmware_version)


def build_boot_data_request(
    sequence: int,
    data: bytes | bytearray | memoryview,
) -> bytes:
    """Build one host type-3 frame with an absolute packet sequence number."""

    if not isinstance(sequence, int) or not 0 <= sequence <= 0xFFFFFFFF:
        raise ProtocolError("bootloader sequence must fit in an unsigned 32-bit integer")
    try:
        payload = bytes(data)
    except TypeError as exc:
        raise ProtocolError("bootloader data must be bytes-like") from exc
    if len(payload) > BOOT_DATA_SIZE:
        raise ProtocolError(f"bootloader data exceeds the HID maximum of {BOOT_DATA_SIZE} bytes")
    return build_boot_frame(
        BootFrameType.HOST_TRANSFER_DATA,
        struct.pack("<I", sequence) + payload,
    )


def _coerce_device_boot_frame(frame: BootFrame | bytes) -> BootFrame:
    if isinstance(frame, BootFrame):
        return frame
    if not isinstance(frame, bytes):
        raise ProtocolError("bootloader response must be BootFrame or bytes")
    # A full HID response begins with report ID 1.  A bare common frame begins
    # with device magic 81 00 ee.  Parsing the two forms separately prevents the
    # report ID from being mistaken for part of the updater frame.
    if len(frame) >= 4 and frame[0] == 1 and frame[1:4] == b"\x81\x00\xee":
        return from_boot_hid_report(frame)
    return parse_boot_frame(frame, device_response=True)


def decode_boot_ack(frame: BootFrame | bytes) -> int:
    """Return the authoritative next expected packet from a type-2 reply."""

    parsed = _coerce_device_boot_frame(frame)
    if parsed.frame_type != BootFrameType.DEVICE_NEXT_PACKET_ACK:
        raise ProtocolError(f"expected bootloader type 2 ACK, got type {parsed.frame_type}")
    if len(parsed.payload) != 4:
        raise ProtocolError("bootloader type 2 ACK payload must be exactly four bytes")
    return struct.unpack("<I", parsed.payload)[0]


def decode_boot_terminal_status(frame: BootFrame | bytes) -> bool:
    """Decode type 5; true means received RAM bytes passed header MD5.

    This does *not* prove that SPI erase/write has completed or succeeded.  The
    bootloader sends the success byte first, waits roughly 200 ms, then programs
    flash without checking or reporting the driver return values.
    """

    parsed = _coerce_device_boot_frame(frame)
    if parsed.frame_type != BootFrameType.DEVICE_TERMINAL_STATUS:
        raise ProtocolError(f"expected bootloader type 5 status, got type {parsed.frame_type}")
    if parsed.payload not in (b"\x00", b"\x01"):
        raise ProtocolError("bootloader type 5 payload must be one byte 00 or 01")
    return parsed.payload == b"\x01"

